
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: subha
    networks:
      - spring-net

  postgres:
    image: postgres 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: subha
      POSTGRES_DB: portfolio
    ports:
      - "5433:5432"
    volumes:
      - postgres-s-data:/var/lib/postgresql/data
    networks:
      - spring-net
    
volumes:
  postgres-s-data:
networks:
  spring-net:
    driver: bridge